stan-core:
  stanPath: .stan
  excludes:
    - '**/.tsbuild/**'
    - '**/*.tsbuildinfo'
    - CHANGELOG.md
    - package-lock.json
  imports:
    '@karmaniverous/karmanivero.us':
      - ../karmanivero.us/collections/_posts/2024-11-17-using-two-whatsapp-accounts-on-the-same-desktop.md
      - ../karmanivero.us/collections/_posts/2025-06-29-directing-tel-links-to-whatsapp-desktop-in-windows.md
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    knip:
      script: npm run knip
      warnPattern: Configuration hints
    make: npx dotenvx run -e NO_COLOR=1 --ignore=MISSING_ENV_FILE -- npm run make
